### ISSUE TITLE
you have spaghetti code

### ISSUE THREAD

**Issue by plesnerd** [plesnerd/plesnerd.github.io#1]
your code is bad

**Comment by plesnerd** [comment]
😭ok

**Comment by Qwerty-Qwerty88** [comment]
why are you talking to yourself

**Comment by plesnerd** [comment]
no friend 😭

**Comment by plesnerd** [comment]
![IMG_2765](https://github.com/plesnerd/plesnerd.github.io/assets/147000740/f79d0e20-456f-4bc1-a140-003925b6a802)
i need to share this
